layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

permalink: /:categories/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

paginate: 9
paginate_path: "/blog/page:num/"

projects: 6

excerpt_separator: <!--more-->

personal:
  links:
    doyoubuzz: "https://www.doyoubuzz.com/wilfried-jeanniard"